<<<<<<< HEAD
services:
  - type: web
    name: bankruptcy-forecasting-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
=======
services:
  - type: web
    name: bankruptcy-predictor
    env: python
    buildCommand: ""
    startCommand: python app.py
    plan: free
    region: oregon


>>>>>>> e6660292faee72ed70a9d298713fcca0118d5b2e
